# Generated by Django 6.0 on 2025-12-23 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_type', models.CharField(choices=[('TEMP_OUT', 'Tạm vắng'), ('TEMP_IN', 'Tạm trú')], max_length=10)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, null=True)),
                ('destination', models.CharField(blank=True, max_length=300, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_records', to='core.household')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_records', to='core.person')),
            ],
        ),
    ]
